services:
  - type: web
    name: hotel-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: APP_NAME
        value: HotelBackend
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: hotel-7b166e7-hosangg113-28fa.d.aivencloud.com
      - key: DB_PORT
        value: "25532"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LOG_CHANNEL
        value: stderr
