export default {
  name: "Colson House",
  subtitle: "Brighton",
  tagline: "A boutique Georgian townhouse hotel in the heart of Brighton's Kemp Town — one street from the seafront since 1997.",
  phone: "+441273044306",
  email: "info@colsonhouse.co.uk",
  address: "17 Upper Rock Gardens, Brighton, BN2 1QE",
  bookingUrl: "/availability",
  ftbUrl: "https://booking-directly.com/widgets/2FtcovmkVyAu40RKQAmygormLwDtQaaiPqUPvmBAmAEMHQRdo3lLtMhkIBSWY/properties",
  social: {
    instagram: "https://instagram.com/colsonhouse",
    facebook: "https://facebook.com/colsonhouse",
  },
  nav: [
    { label: "Home",              path: "/" },
    { label: "Our Rooms",         path: "/rooms",       hash: "rooms" },
    { label: "Offers",            path: "/offers",      hash: "offers" },
    { label: "Local Attractions", path: "/attractions", hash: "attractions" },
    { label: "Reviews",           path: "/reviews",     hash: "reviews" },
    { label: "Contact",           path: "/contact",     hash: "contact" },
  ],
  footer: {
    explore: [
      { label: "Our Rooms", path: "/rooms" },
      { label: "Check Availability", path: "/availability" },
      { label: "Special Offers", path: "/offers" },
      { label: "Local Attractions", path: "/attractions" },
      { label: "Gallery", path: "/gallery" },
    ],
    information: [
      { label: "Check-In & Check-Out", path: "/checkin" },
      { label: "Parking", path: "/parking" },
      { label: "Terms & Conditions", path: "/terms" },
      { label: "Privacy Policy", path: "/privacy" },
      { label: "Cookie Policy", path: "/cookies" },
    ],
  },
  copyright: "© 2024 Colson House. All rights reserved.",
  builtBy: "Website by Hodfords",
}
