<?php

namespace Database\Seeders;

use App\Models\Room;
use Illuminate\Database\Seeder;

class RoomSeeder extends Seeder
{
    public function run(): void
    {
        Room::truncate();

        $rooms = [
            [
                'name'             => 'Room 1, Deluxe Double Room',
                'size'             => 26,
                'description'      => 'Guests will have a special experience as this double room offers a fireplace. Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV. The unit offers 1 bed.',
                'long_description' => 'Guests will have a special experience as this double room offers a fireplace. Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV. The unit offers 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Broadband/High Speed Internet Access',
                    'Central Heating', 'Daily Housekeeping', 'Designer Toiletries', 'Egyptian Cotton Linen',
                    'Electric Shaver Point', 'En Suite', 'LCD/Plasma Television', 'Remote Control TV',
                    'Shower EnSuite', 'Tea/Coffee', 'TV In Room', 'Wash Hand Basin EnSuite', 'WC EnSuite',
                    'WI-FI Internet Access', 'Wifi Free', 'Windows open', 'Complimentary Toiletries',
                    'Digital Television Channels', 'Flat Screen TV', 'Fridge', 'Linen & Towels Supplied',
                    'Private Bathroom', 'Work Desk',
                ],
                'images' => [
                    '/images/rooms/room-0/room0.avif',
                    '/images/rooms/room-0/room0_1.webp',
                    '/images/rooms/room-0/room0_2.webp',
                    '/images/rooms/room-0/room0_3.webp',
                    '/images/rooms/room-0/room0_4.webp',
                    '/images/rooms/room-0/room0_5.webp',
                    '/images/rooms/room-0/room0_6.webp',
                    '/images/rooms/room-0/room0_7.webp',
                    '/images/rooms/room-0/room0_8.webp',
                    '/images/rooms/room-0/room0_9.webp',
                ],
            ],
            [
                'name'             => 'Room 2, Four Poster Room',
                'size'             => 28,
                'description'      => 'Guests will have a special experience as this double room offers a fireplace. Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers a four poster bed.',
                'long_description' => 'Guests will have a special experience as this double room offers a fireplace. Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers a four poster bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Broadband/High Speed Internet Access',
                    'Central Heating', 'Complimentary Toiletries', 'Daily Housekeeping', 'Designer Toiletries',
                    'Digital Television Channels', 'Egyptian Cotton Linen', 'En Suite', 'Flat Screen TV',
                    'Four Poster Bed', 'Fridge', 'Private Bathroom', 'Shower EnSuite', 'Tea/Coffee',
                    'Television', 'TV In Room', 'Wash Hand Basin EnSuite', 'WC EnSuite',
                    'WI-FI Internet Access', 'Wifi Free', 'Windows open',
                ],
                'images' => [
                    '/images/rooms/room-1/rroom1.webp',
                    '/images/rooms/room-1/rroom1_1.webp',
                    '/images/rooms/room-1/rroom1_2.webp',
                    '/images/rooms/room-1/rroom1_3.webp',
                    '/images/rooms/room-1/rroom1_4.webp',
                    '/images/rooms/room-1/rroom1_5.webp',
                    '/images/rooms/room-1/rroom1_6.webp',
                    '/images/rooms/room-1/rroom1_7.webp',
                    '/images/rooms/room-1/rroom1_8.webp',
                    '/images/rooms/room-1/rroom1_9.webp',
                    '/images/rooms/room-1/rroom1_10.webp',
                    '/images/rooms/room-1/rroom1_11.webp',
                    '/images/rooms/room-1/rroom1_12.webp',
                ],
            ],
            [
                'name'             => 'Room 3, Standard Double',
                'size'             => 18,
                'description'      => 'Featuring free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room has a wardrobe, an electric kettle, flat-screen TV, as well as chocolate for guests. The unit has 1 bed.',
                'long_description' => 'Featuring free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room has a wardrobe, an electric kettle, flat-screen TV, as well as chocolate for guests. The unit has 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'Central Heating', 'Daily Housekeeping', 'Egyptian Cotton Linen', 'Flat Screen TV',
                    'Fridge', 'Kettle', 'Private Bathroom', 'Shower EnSuite', 'Tea/Coffee', 'Television',
                    'TV In Room', 'Wash Hand Basin EnSuite', 'WC EnSuite', 'WI-FI Internet Access',
                    'Wifi Free', 'Windows open', 'Work Desk',
                ],
                'images' => [
                    '/images/rooms/room-2/rroom2.webp',
                    '/images/rooms/room-2/rroom2_2.webp',
                    '/images/rooms/room-2/rroom2_3.webp',
                    '/images/rooms/room-2/rroom2_4.webp',
                    '/images/rooms/room-2/rroom2_5.webp',
                    '/images/rooms/room-2/rroom2_6.webp',
                    '/images/rooms/room-2/rroom2_7.webp',
                    '/images/rooms/room-2/rroom2_8.webp',
                    '/images/rooms/room-2/rroom2_9.webp',
                    '/images/rooms/room-2/rroom2_10.webp',
                ],
            ],
            [
                'name'             => 'Room 4, Deluxe Balcony Room',
                'size'             => 24,
                'description'      => 'This double room provides a fireplace. A seating area with a flat-screen TV, a desk, a balcony and a private bathroom are provided in this double room. The unit offers 1 bed.',
                'long_description' => 'This double room provides a fireplace. A seating area with a flat-screen TV, a desk, a balcony and a private bathroom are provided in this double room. The unit offers 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Balcony',
                    'Broadband/High Speed Internet Access', 'Central Heating', 'Complimentary Toiletries',
                    'Daily Housekeeping', 'Designer Toiletries', 'Egyptian Cotton Linen', 'Flat Screen TV',
                    'Fridge', 'Kettle', 'Linen & Towels Supplied', 'Private Bathroom', 'Remote Control TV',
                    'Shower EnSuite', 'Tea/Coffee', 'Television', 'TV In Room', 'Wash Hand Basin EnSuite',
                    'WC EnSuite', 'WI-FI Internet Access', 'Wifi Free', 'Windows open',
                ],
                'images' => [
                    '/images/rooms/room-3/rroom3.webp',
                    '/images/rooms/room-3/rroom3_1.webp',
                    '/images/rooms/room-3/rroom3_2.webp',
                    '/images/rooms/room-3/rroom3_3.webp',
                    '/images/rooms/room-3/rroom3_4.webp',
                    '/images/rooms/room-3/rroom3_5.webp',
                    '/images/rooms/room-3/rroom3_6.webp',
                    '/images/rooms/room-3/rroom3_7.webp',
                    '/images/rooms/room-3/rroom3_8.webp',
                    '/images/rooms/room-3/rroom3_9.webp',
                    '/images/rooms/room-3/rroom3_10.webp',
                    '/images/rooms/room-3/rroom3_11.webp',
                    '/images/rooms/room-3/rroom3_12.webp',
                    '/images/rooms/room-3/rroom3_13.webp',
                ],
            ],
            [
                'name'             => 'Room 5, Standard Double',
                'size'             => 18,
                'description'      => 'Featuring free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room has a wardrobe, an electric kettle, flat-screen TV, as well as chocolate for guests. The unit has 1 bed.',
                'long_description' => 'Featuring free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room has a wardrobe, an electric kettle, flat-screen TV, as well as chocolate for guests. The unit has 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Broadband/High Speed Internet Access',
                    'Complimentary Toiletries', 'Daily Housekeeping', 'Designer Toiletries',
                    'Digital Television Channels', 'Egyptian Cotton Linen', 'Flat Screen TV', 'Fridge',
                    'Kettle', 'Linen & Towels Supplied', 'Shower EnSuite', 'Tea/Coffee',
                    'Wash Hand Basin EnSuite', 'WI-FI Internet Access', 'Wifi Free', 'Windows open',
                    'Work Desk with Lamp',
                ],
                'images' => [
                    '/images/rooms/room-4/rroom4.webp',
                    '/images/rooms/room-4/rroom4_1.webp',
                    '/images/rooms/room-4/rroom4_2.webp',
                    '/images/rooms/room-4/rroom4_3.webp',
                    '/images/rooms/room-4/rroom4_4.webp',
                    '/images/rooms/room-4/rroom4_5.webp',
                    '/images/rooms/room-4/rroom4_6.webp',
                    '/images/rooms/room-4/rroom4_7.webp',
                    '/images/rooms/room-4/rroom4_8.webp',
                    '/images/rooms/room-4/rroom4_9.webp',
                    '/images/rooms/room-4/rroom4_10.webp',
                    '/images/rooms/room-4/rroom4_11.webp',
                    '/images/rooms/room-4/rroom4_12.webp',
                    '/images/rooms/room-4/rroom4_13.webp',
                    '/images/rooms/room-4/rroom4_14.webp',
                    '/images/rooms/room-4/rroom4_15.webp',
                ],
            ],
            [
                'name'             => 'Room 6, Deluxe Double',
                'size'             => 22,
                'description'      => 'Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers 1 bed.',
                'long_description' => 'Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Broadband/High Speed Internet Access',
                    'Complimentary Toiletries', 'Daily Housekeeping', 'Designer Toiletries',
                    'Electric Shaver Point', 'En Suite', 'Flat Screen TV', 'Fridge', 'Kettle',
                    'Linen & Towels Supplied', 'Private Bathroom', 'Remote Control TV', 'Shower EnSuite',
                    'Tea/Coffee', 'Wash Hand Basin EnSuite', 'WC EnSuite', 'WI-FI Internet Access',
                    'Wifi Free', 'Windows open', 'Work Desk',
                ],
                'images' => [
                    '/images/rooms/room-5/rroom5.webp',
                    '/images/rooms/room-5/rroom5_1.webp',
                    '/images/rooms/room-5/rroom5_2.webp',
                    '/images/rooms/room-5/rroom5_3.webp',
                    '/images/rooms/room-5/rroom5_5.webp',
                    '/images/rooms/room-5/rroom5_6.webp',
                    '/images/rooms/room-5/rroom5_7.webp',
                    '/images/rooms/room-5/rroom5_8.webp',
                    '/images/rooms/room-5/rroom5_9.webp',
                    '/images/rooms/room-5/rroom5_10.webp',
                    '/images/rooms/room-5/rroom5_11.webp',
                    '/images/rooms/room-5/rroom5_12.webp',
                    '/images/rooms/room-5/rroom5_13.webp',
                    '/images/rooms/room-5/rroom5_14.webp',
                    '/images/rooms/room-5/rroom5_15.webp',
                ],
            ],
            [
                'name'             => 'Room 7, Small Single',
                'size'             => 12,
                'description'      => 'A TV, DVD player and tea/coffee making facilities are featured in this room.',
                'long_description' => 'A TV, DVD player and tea/coffee making facilities are featured in this room.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Broadband/High Speed Internet Access',
                    'Central Heating', 'Complimentary Toiletries', 'Daily Housekeeping', 'Designer Toiletries',
                    'Desk Chair', 'Egyptian Cotton Linen', 'Electric Shaver Point', 'En Suite',
                    'Heating Throughout Property', 'TV In Room', 'Wash Hand Basin EnSuite', 'WC EnSuite',
                    'WI-FI Internet Access', 'Wifi Free', 'Windows open', 'Work Desk',
                ],
                'images' => [
                    '/images/rooms/room-6/rroom6.webp',
                    '/images/rooms/room-6/rroom6_1.webp',
                    '/images/rooms/room-6/rroom6_2.webp',
                    '/images/rooms/room-6/rroom6_3.webp',
                    '/images/rooms/room-6/rroom6_4.webp',
                    '/images/rooms/room-6/rroom6_5.webp',
                ],
            ],
            [
                'name'             => 'Room 8, Deluxe Double',
                'size'             => 22,
                'description'      => 'Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers 1 bed.',
                'long_description' => 'Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Broadband/High Speed Internet Access',
                    'Central Heating', 'Complimentary Toiletries', 'Daily Housekeeping', 'Designer Toiletries',
                    'Egyptian Cotton Linen', 'Electric Shaver Point', 'En Suite', 'Flat Screen TV', 'Fridge',
                    'Kettle', 'Private Bathroom', 'Shower EnSuite', 'Tea/Coffee', 'TV In Room',
                    'Wash Hand Basin EnSuite', 'WC EnSuite', 'WI-FI Internet Access', 'Wifi Free',
                    'Windows open', 'Work Desk',
                ],
                'images' => [
                    '/images/rooms/room-7/rroom7.webp',
                    '/images/rooms/room-7/rroom7_1.webp',
                    '/images/rooms/room-7/rroom7_2.webp',
                    '/images/rooms/room-7/rroom7_3.webp',
                    '/images/rooms/room-7/rroom7_4.webp',
                    '/images/rooms/room-7/rroom7_5.webp',
                    '/images/rooms/room-7/rroom7_6.webp',
                    '/images/rooms/room-7/rroom7_7.webp',
                    '/images/rooms/room-7/rroom7_8.webp',
                    '/images/rooms/room-7/rroom7_9.webp',
                    '/images/rooms/room-7/rroom7_10.webp',
                    '/images/rooms/room-7/rroom7_11.webp',
                ],
            ],
            [
                'name'             => 'Room 9, Split Level Double',
                'size'             => 24,
                'description'      => 'Guests will have a special experience as this double room offers a fireplace. Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers 1 bed.',
                'long_description' => 'Guests will have a special experience as this double room offers a fireplace. Offering free toiletries, this double room includes a private bathroom with a shower and a hairdryer. This double room features a seating area, a wardrobe, flat-screen TV, as well as chocolate for guests. The unit offers 1 bed.',
                'price'            => 0,
                'amenities'        => [
                    'ALL bedrooms Non Smoking', 'ALL Rooms Non-Smoking', 'Central Heating',
                    'Complimentary Toiletries', 'Daily Housekeeping', 'Designer Toiletries',
                    'Egyptian Cotton Linen', 'Electric Shaver Point', 'En Suite', 'Flat Screen TV', 'Fridge',
                    'Linen & Towels Supplied', 'Television', 'TV In Room', 'Wash Hand Basin EnSuite',
                    'WC EnSuite', 'WI-FI Internet Access', 'Wifi Free', 'Windows open', 'Work Desk',
                ],
                'images' => [
                    '/images/rooms/room-8/rroom8.webp',
                    '/images/rooms/room-8/rroom8_1.webp',
                    '/images/rooms/room-8/rroom8_2.webp',
                    '/images/rooms/room-8/rroom8_3.webp',
                    '/images/rooms/room-8/rroom8_4.webp',
                    '/images/rooms/room-8/rroom8_5.webp',
                    '/images/rooms/room-8/rroom8_6.webp',
                    '/images/rooms/room-8/rroom8_7.webp',
                    '/images/rooms/room-8/rroom8_8.webp',
                    '/images/rooms/room-8/rroom8_9.webp',
                    '/images/rooms/room-8/rroom8_10.webp',
                    '/images/rooms/room-8/rroom8_11.webp',
                    '/images/rooms/room-8/rroom8_12.webp',
                    '/images/rooms/room-8/rroom8_13.webp',
                    '/images/rooms/room-8/rroom8_14.webp',
                ],
            ],
        ];

        foreach ($rooms as $room) {
            Room::create($room);
        }
    }
}
